# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(375, 296)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(23, 10, 121, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 141, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 70, 81, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 81, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(100, 150, 81, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 180, 131, 21))
        self.label_6.setObjectName("label_6")
        self.title = QtWidgets.QLineEdit(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(150, 10, 201, 20))
        self.title.setObjectName("title")
        self.roasting = QtWidgets.QLineEdit(self.centralwidget)
        self.roasting.setGeometry(QtCore.QRect(150, 40, 201, 20))
        self.roasting.setObjectName("roasting")
        self.type = QtWidgets.QLineEdit(self.centralwidget)
        self.type.setGeometry(QtCore.QRect(150, 70, 201, 20))
        self.type.setObjectName("type")
        self.description = QtWidgets.QLineEdit(self.centralwidget)
        self.description.setGeometry(QtCore.QRect(90, 100, 281, 31))
        self.description.setObjectName("description")
        self.price = QtWidgets.QLineEdit(self.centralwidget)
        self.price.setGeometry(QtCore.QRect(150, 150, 201, 20))
        self.price.setObjectName("price")
        self.package_volume = QtWidgets.QLineEdit(self.centralwidget)
        self.package_volume.setGeometry(QtCore.QRect(150, 180, 201, 20))
        self.package_volume.setObjectName("package_volume")
        self.btn = QtWidgets.QPushButton(self.centralwidget)
        self.btn.setGeometry(QtCore.QRect(180, 210, 121, 23))
        self.btn.setObjectName("btn")
        self.error = QtWidgets.QLabel(self.centralwidget)
        self.error.setGeometry(QtCore.QRect(20, 210, 111, 16))
        self.error.setText("")
        self.error.setObjectName("error")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 375, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Название сорта:"))
        self.label_2.setText(_translate("MainWindow", "Степень обжарки:"))
        self.label_3.setText(_translate("MainWindow", "Тип кофе:"))
        self.label_4.setText(_translate("MainWindow", "Описание:"))
        self.label_5.setText(_translate("MainWindow", "Цена:"))
        self.label_6.setText(_translate("MainWindow", "Объём упаковки:"))
        self.btn.setText(_translate("MainWindow", "PushButton"))
